### ISSUE TITLE
Variable "prefix" does not exist.

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#2620] opened 2020-01-23 01:11 UTC
There's any error occurring when I try to view a node in the admin:

Variable `prefix` does not exist.

E.g. admin/nodes/1

`vendor/kunstmaan/node-bundle/Resources/views/Form/formWidgets.html.twig:79`

Where does the `prefix` variable come from?

**Comment by acrobat** [comment] 2020-01-23 11:32
@henrypenny thanks for the report! This issues was caused by #2529 and I've created a PR to fix it. You can temporary switch back to v5.3.10 to workaround the issue, this will be fixed in v5.4.1

**Comment by acrobat** [comment] 2020-01-23 13:26
Fixed in #2621

**Closed by acrobat** 2020-01-23 13:26 UTC
Labels: Type: Bug

**Comment by acrobat** [comment] 2020-01-23 16:01
@henrypenny [v5.4.1](https://github.com/Kunstmaan/KunstmaanBundlesCMS/releases/tag/5.4.1) was released with a fix for this issue
