### ISSUE TITLE
[AdminBundle] Template "form_div_layout.html.twig" cannot be used as a trait.

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#2495] opened 2019-06-04 10:20 UTC
When performing a composer update yesterday, "twig/twig" went from 2.10.0 to 2.11.0.

After this virtually all forms in the admin area were broken with the error:

```Template "form_div_layout.html.twig" cannot be used as a trait.```

Moving back to 2.10.0 fixes it.

Symfony 4.2.9
PHP 7.3.5
Ubuntu 18.04
Bundles 5.3.1

**Comment by acrobat** [comment] 2019-06-04 20:26
It seems to be related to twig itself, see twigphp/Twig#3051 as others have the same issue as well. Let's wait for some more info in that issue to see what the cause is for this.

**Comment by acrobat** [comment] 2019-06-05 07:01
@iknowfoobar it seems that manually removing the cache folder after the upgrade seems to fix the issue. See twigphp/Twig#3051

**Comment by iknowfoobar** [comment] 2019-06-05 08:18
Hi @acrobat , thanks for the update. I can confirm that going to 2.11.1 works fine for us.

**Comment by iknowfoobar** [comment] 2019-06-05 08:55
@acrobat Sorry spoke too soon. Clearing the cache again using the symfony command results in the same error. The site only works if the cache directory is manually cleared.

I'll keep an eye on the Twig issue till it is resolved, thanks for logging it.

**Comment by acrobat** [comment] 2019-06-05 11:26
Closing this issue, [twig 2.11.2](https://github.com/twigphp/Twig/issues/3051#issuecomment-499042759) is released with a fix!

**Closed by acrobat** 2019-06-05 11:26 UTC
