### ISSUE TITLE
When selecting a piece of text on Safari/yosemite in the ckeditor, the pagescrolls to the bottom

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#902] opened 2016-01-18 10:47 UTC

**Comment by FVKVN** [comment] 2016-02-11 09:56
Can't reproduce, @roderik can you provide an example?

**Comment by roderik** [comment] 2016-02-11 09:59
I've demonstrated it to several ppl, including @VickyDeschrijver i believe

**Comment by dbeerten** [comment] 2016-06-17 07:14
Not reproducible. @diskwriter Close this one?

**Closed** 2016-06-20 07:52 UTC
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix
