### ISSUE TITLE
Unable to drag & drop PageParts between sections

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#3072] opened 2022-02-07 08:28 UTC
Hi,

A while ago we've updated some of our older Kunstmaan projects to version 5.8. All went fine, but recently we've discovered that PageParts can no longer be moved to other sections or within the same section via drag & drop.

I've made a screen capture which shows the problem: https://imgur.com/nDodaXr. 

Is this a known issue or does this have something to do with configuration? Haven't been able to find anything about this in the documentation or Github issues so far.

Kind regards,
Kevin

**Comment by acrobat** [comment] 2022-02-18 14:13
@KevinSleegers do you add custom JS to the cms admin or see any js error in the browser? As I've tested this functionality within an existing website that was upgraded to 5.10. I was still able to drag and drop within the same region and move pageparts to different regions on the page.

I don't think there were big changes to this part between 5.8 and 5.10, but can you try to update to 5.10 to make sure it's not a bug in 5.8 (this version won't receive bugfixes anymore)

**Comment by acrobat** [comment] 2023-02-09 11:47
Closing this issue for now. If you still have this problem, open a new issue or reopen this issue.

**Closed as completed by acrobat** 2023-02-09 11:47 UTC
