### ISSUE TITLE
Make it easier to override controllers

### ISSUE THREAD

**Issue by waaghals** [Kunstmaan/KunstmaanBundlesCMS#403] opened 2015-05-11 09:14 UTC
In our project users with the role `ROLE_ADMIN` should be able to edit users as well.
But the `UsersController` only checks for the role `ROLE_SUPER_ADMIN` so I had to override the controller by extending the bundle.

This was harder then it should have been.
Because I'm overriding the controllers using bundle inheritance the annotations no longer work.
I tried overriding the routes but this didn't work because I got a curricular reference in the routing definition.

My current solution was just to copy the controller into my child bundle and make the modification's there.

Imho the controllers should be services with XML routing definitions so they can easily be overridden.

**Comment by wimvds** [comment] 2015-05-11 09:16
Err, why didn't you just add the ROLE_SUPER_ADMIN to your Administrators group? That would have solved the issue without you having to write any code...

**Comment by waaghals** [comment] 2015-05-11 11:37
Because then the users would have had all the options the superadmin role had. This wasn't desired.

**Comment by sandergo90** [comment] 2016-08-17 09:00
@jockri close, the new permission system will need to be able to handle this

**Comment by jockri** [comment] 2016-10-11 10:54
Duplicate of #1329

**Closed by jockri** 2016-10-11 10:54 UTC
