### ISSUE TITLE
EventDispatcher deprecation

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2724] opened 2020-09-04 06:58 UTC
User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.

**Comment by acrobat** [comment] 2020-09-04 07:05
Closing as a duplicate of #2722

**Closed by acrobat** 2020-09-04 07:05 UTC

**Comment by dannyvw** [comment] 2020-09-04 07:15
@acrobat sorry had not refreshed my page :(
