### ISSUE TITLE
[Form] Required fields aren't checked

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1607] opened 2017-09-29 13:50 UTC
When adding a file upload pagepart to a form the label is not validated while saving the node. The label is displayed as required.  I expected it to check if the required fields are met (@Assert\NotBlank()) on the entity.

**Comment by delboy1978uk** [comment] 2017-12-04 09:45
Can you give us some more steps to reproduce this?

**Comment by dannyvw** [comment] 2017-12-04 10:16
* Create a new form page node
* Add an file upload pagepart to the node and leave the label field blank
* Save node
* Preview the form page node and you will get an 500 error

The file upload pagepart is an example. This problem occurs by different pageparts.

**Comment by delboy1978uk** [comment] 2017-12-05 14:53
I can reproduce the required label field not complaining when blank upon submission, this is because setting required to true doesn't actually do any validation 😑

I don't get any type of 500. Could you post a stack trace?

Also, according to the Symfony docs:
```
If true, an HTML5 required attribute will be rendered. The corresponding label will also render with a required class. This is superficial and independent from validation.
```

The label is part of the `AbstractFormPagePart`, and so all page parts extend this. I'm not sure if that could cause problems forcing the label to assert `NotBlank()`. I copied the property into the `FileUploadPagePart` overriding the parent, and put a `NotBlank()` on there, and it all worked fine. 

Not sure if that's the best approach though. @Devolicious any thoughts?

**Comment by dannyvw** [comment] 2017-12-05 15:50
@delboy1978uk Yeah i know what the required attributes does. 

I have tested it again and you get only the error if you submit the form. Error:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'label' cannot be null

**Comment by delboy1978uk** [comment] 2017-12-05 16:15
that's strange, I'm not getting the db error. The label field is defined in `AbstractFormPagePart`, and the Doctrine annotation is :
```* @ORM\Column(type="string", nullable=true)```
Unless your own child page part class has overridden the property?

**Comment by dannyvw** [comment] 2017-12-06 07:17
@delboy1978uk Strange.. i have only a file upload pagepart and a submit button. The db table is kuma_form_submission_fields and that label field cannot be null.

**Comment by delboy1978uk** [comment] 2017-12-06 08:47
Good morning @dannyvw, I have now reproduced your error! Previewing it was fine, but submitting through the front end gave me the same error! Indeed, https://github.com/delboy1978uk/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php#L50 is not nullable. 
Based on that, my previous doubt about adding `Assert\NotBlank()` to the `AbstractFormPagePart` has gone, I believe we can safely force it to be a required field. I'll check with the team and get the fix in!

**Comment by Numkil** [comment] 2017-12-07 12:58
@dannyvw Closing because related pull request has been merged. If there are any more problems then do not hesitate to reopen this issue.

**Closed by Numkil** 2017-12-07 12:58 UTC
