### ISSUE TITLE
Deprecations that will fail in Symfony 4

### ISSUE THREAD

**Issue by deZinc** [Kunstmaan/KunstmaanBundlesCMS#1815] opened 2018-02-09 07:48 UTC
Some examples (but there are more to be found I guess):

> User Deprecated: The "kunstmaan_admin.domain_configuration" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

> User Deprecated: The "kunstmaan_admin.adminroute.helper" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

> Passing a "Symfony\Component\Translation\MessageSelector" instance into the "Symfony\Component\Translation\Translator::__construct" as a second argument is deprecated since Symfony 3.4 and will be removed in 4.0. Inject a "Symfony\Component\Translation\Formatter\MessageFormatterInterface" implementation instead.

> User Deprecated: Returning null from "Kunstmaan\AdminBundle\Security\OAuthAuthenticator::getCredentials()" is deprecated since Symfony 3.4 and will throw an \UnexpectedValueException in 4.0. Return false from "Kunstmaan\AdminBundle\Security\OAuthAuthenticator::supports()" instead.

**Comment by acrobat** [comment] 2018-02-09 08:12
The deprecation about the `translator::__construct` should be fixed when #1792 is merged

**Comment by deZinc** [comment] 2018-02-09 08:54
@sandergo90 is also working on some deprecations.

**Comment by acrobat** [comment] 2018-02-09 08:57
Yes! I'm also looking into a way to easily migrate to fix the `User Deprecated: Bundle inheritance is deprecated as of 3.4 and will be removed in 4.0.` deprecation caused by extending the fos userbundle

**Comment by Numkil** [comment] 2018-07-31 13:59
The discussed deprecations have been merged and are also mentioned in the sf4 roadmap so this is duplicate

**Closed by Numkil** 2018-07-31 13:59 UTC
