### ISSUE TITLE
[AdminBundle] LinkChooser on CKEDITOR

### ISSUE THREAD

**Issue by jverdeyen** [Kunstmaan/KunstmaanBundlesCMS#1434] opened 2017-01-12 12:02 UTC
When using the "Browse Server" button (while creating a link in a TextPagePart with CKEDITOR) you still get the new LinkChooser-link, for example: [NT8].

All links in the TextPagePart need to be replaced by the real links and for usability this should also show the slug in the CKEDITOR.

<img width="392" alt="screenshot 2017-01-12 13 02 20" src="https://cloud.githubusercontent.com/assets/117409/21889070/61b1858e-d8c7-11e6-956a-e5af53aea4a5.png">

**Comment by Devolicious** [comment] 2017-01-12 12:30
@jverdeyen, this is intended behaviour. We added this functionality to the CKeditor to keep it consistent with the linkchooser. LinkChoosers and CKeditor pageparts should implement the replace_url twig filter as stated in https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/UPGRADE-4.0.md

Unfortunally we cannot do some magic on the CKeditor as we do with the linkchoosers. We need the token to be saved to the database and not the real link. Otherwise it defeats the whole purpose of this functionallity.

**Comment by mlebkowski** [comment] 2017-01-12 13:52
You basically chose to use some kind of BBcode [instead of a transformer](https://github.com/syzygypl/kunstmaan-extra-bundle/blob/master/src/Form/Extension/DataTransformer/NodeTranslationToUrlTransformer.php)? This should be done on the backend, i.e. `WysiwygType` and `LinkChooser` should reverse-transform the URL to a token/nodeId. This way you would operate on URL-s in the interface, more human friendly and „normal”; and it would keep reference to the page/node instead of a string, so it would have the benefit of being up to date when the URL changes. And it would work without the `replace_url` in most of the cases.

**Comment by Devolicious** [comment] 2017-01-12 15:53
Hi @mlebkowski,

I think there are some issues with that approach. First, a datatransformer will work on forms in the admin (not sure about the `WysiwygType` with large block of html/text), but how do you see this working on the frontend when you have saved a nodetranslation ID to the database? Do you still use the `replace_url` for this? 

Second, how do you handle external url's? In the code you show you need to match with an internal url, meaning that external url's are not excepted. Also, this would mean that when a url is outdated, you would get an form error and manually have to select the correct page again. On a small site this is no issue but when you have a lot of pages with different admins this might not be an easy task.

**Comment by mlebkowski** [comment] 2017-01-13 09:07
>  Also, this would mean that when a url is outdated, you would get an form error and manually have to select the correct page again. 

You would not. `NodeTranslation` is stored in the database, so every time a form is displayed, the transformer converts it to a URL, and then back again when the form’s entity is saved to the database. It’s just how a `\DateTime` object is represented by a string in the `FormView`, but again as an object in your entities. So you won’t ever see an outdated URL in the Form, because it was *just* calculated from the node translation.

> First, a datatransformer will work on forms in the admin (not sure about the WysiwygType with large block of html/text), but how do you see this working on the frontend when you have saved a nodetranslation ID to the database?

Yes, this would require different treatment on the frontend / in the templates. Instead of `resource.url` (or `resource.url | replace_url` it would be `resource.nodetranslation.url`. To avoid the obvious BC break, the transformer would be disabled by default in `3.x`, enabled using a form option for those who want this functionality, and then enabled by default in `4.x`.

> Second, how do you handle external url's? In the code you show you need to match with an internal url, meaning that external url's are not excepted

You would not. But I wouldn’t want to either. Keeping two different types of values in one field is against the basic database design principles. You either:

  1. create two fields, one textual for external / free form URLs, and the second for `NodeTranslation` (see how the `MenuItem` does this) 
  2. Always store `NodeTranslation` and use some kind of `RedirectPage` to forward to an external URL
  3. If you really want to, the `Transformer` may pass the URL as-is if it does not find a match (instead of throwing a `TransformationException` as in my example), and then handle the situation in the setter in the entity (if you get a `NodeTranslation`, save a reference, otherwise save a string to a different field). This could be handled by a trait to reduce the boilerplate.

I use this approach in both small sites and a bunch of large ones (> 750 pages).


The worst part about this implementation is that I don’t need it (I have my own solution I linked earlier), I feel there are far better solutions (see above) and I don’t think there is a way to disable it.

**Comment by Devolicious** [comment] 2017-01-13 09:54
Ok but the main issue here is the CKeditor/WysiwygType. I can see this working for the linkchooser, but yeah it would definitely be BC break. Were not a fan of separating external from internal urls because it might be confusing for clients. For the link chooser you could do some form wizardry to make a single input that would split up into internal/external entity properties.

For a richtext block the story is a little different imo. You would still have to replace the URL with some token because it's a block of html. The replacement can be done with a `DataTransformer` as said earlier but in the templates you can't just do `resource.nodetranslation.url`. How would you handle this? Do you already have a solution?

**Comment by Devolicious** [comment] 2017-02-17 09:33
Since were not going to implement this into the Wysiwyg I'm going to close this issue.

**Closed by Devolicious** 2017-02-17 09:33 UTC
