### ISSUE TITLE
[AdminBundle] Add roles for module management

### ISSUE THREAD

**Issue by arneruy** [Kunstmaan/KunstmaanBundlesCMS#423] opened 2015-05-21 09:34 UTC
A new feature would be to implement roles which could manage specific modules. For example, groups with only the role ROLE_USER_MANAGEMENT would be able to CRUD users, but not CRUD pages. This way it is easier for users to give admins only very specific abilities and access to only their manageable modules. 

Super administrators should still be given all rights. If this group does not exist when migrating, the user should add it manually and give him all new roles. Possible new roles could be:

ROLE_DASHBOARD_MANAGEMENT
ROLE_PAGE_MANAGEMENT
ROLE_MEDIA_MANAGEMENT
ROLE_FORM_SUBMISSIONS_VIEWER
ROLE_USER_MANAGEMENT
ROLE_GROUP_MANAGEMENT
ROLE_ROLE_MANAGEMENT
ROLE_ROBOTS_MANAGEMENT
ROLE_TRANSLATION_MANAGEMENT
ROLE_REDIRECT_MANAGEMENT

**Comment by sandergo90** [comment] 2016-08-17 09:00
@jockri maybe some good start for the new permission system?

**Comment by jockri** [comment] 2016-10-11 10:55
Duplicate of #1329

**Closed by jockri** 2016-10-11 10:55 UTC
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Feature
