### ISSUE TITLE
[MediaBundle] Imagine filters which convert image format no longer work

### ISSUE THREAD

**Issue by molovo** [Kunstmaan/KunstmaanBundlesCMS#2573] opened 2019-10-24 09:55 UTC
Since upgrading to 5.3.5 we're having issues (on multiple Kuma sites) loading images with filters which convert image formats (e.g. PNG -> JPG). The URLs seem to be resolving correctly, but the converted file is never created.

All other images (where the file extension remains the same) are loading fine.

FYI, I suspect this issue is due to a change in one of Kuma's dependencies, as sites which were upgraded early on Monday morning are working - any upgraded later than that are no longer working. However, I'm creating this ticket as I haven't yet been able to track down which dependency is causing it. If I do, I'll update this issue and close

**Comment by acrobat** [comment] 2019-10-25 06:56
From which version did you upgrade? Does downgrading to 5.3.4 resolve the issue?

**Comment by acrobat** [comment] 2020-05-12 18:23
This could have been caused by an incompatibility with liip/imagine 2.2+, but is fixed since v5.3.13.  I'm closing this for now, please leave a comment if it's still an issue.

**Closed by acrobat** 2020-05-12 18:23 UTC
